import {db} from "../db"; import {MockLLM,MockImage,MockVideo,MockTTS} from "../providers/mock"; import * as projects from "./projectService"; import {randomUUID} from "crypto";
const llm=new MockLLM(),image=new MockImage(),video=new MockVideo(),tts=new MockTTS();
export async function generateScript(id:string){const p=projects.get(id);if(!p)throw Error("Projeto não encontrado");if(p.mode==="script")return p;projects.setStatus(id,"generating_script",10);const script=await llm.generateScript({title:p.title,language:p.settings.language,style:p.settings.videoStyle,duration:5});projects.update(id,{script});projects.setStatus(id,"draft",20);return projects.get(id)}
export async function generateScenes(id:string){const p=projects.get(id);if(!p)throw Error("Projeto não encontrado");projects.setStatus(id,"preparing_scenes",30);const scenes=await llm.breakScenes(p.script,JSON.stringify(p));db.prepare("DELETE FROM scenes WHERE project_id=?").run(id);const stmt=db.prepare("INSERT INTO scenes(project_id,narration,visual_description,estimated_duration,context,characters,environment,era,visual_style,status) VALUES(?,?,?,?,?,?,?,?,?,?)");for(const s of scenes)stmt.run(id,s.narration,s.visual_description,s.estimated_duration,s.context,JSON.stringify(s.characters||[]),s.environment||"",s.era||"",s.visual_style||"", "ready");projects.setStatus(id,"draft",40);return projects.get(id)}
export async function generateImages(id:string){const p=projects.get(id);if(!p)throw Error("Projeto não encontrado");projects.setStatus(id,"generating_images",50);for(const s of p.scenes){const prompt=await llm.generateImagePrompt(s,p.visualBible);const r=await image.generate(prompt);db.prepare("UPDATE scenes SET image_prompt=?,image_url=?,status=? WHERE id=?").run(prompt,r.url,"image_ready",s.id)}projects.setStatus(id,"draft",60);return projects.get(id)}
export async function generateAnimations(id:string){const p=projects.get(id);if(!p)throw Error("Projeto não encontrado");projects.setStatus(id,"generating_animations",65);for(const s of p.scenes){const prompt=await llm.generateAnimationPrompt(s);const r=await video.generate(s.imageUrl||"",prompt,s.estimatedDuration);db.prepare("UPDATE scenes SET animation_prompt=?,video_url=?,status=? WHERE id=?").run(prompt,r.url,"video_ready",s.id)}projects.setStatus(id,"draft",75);return projects.get(id)}
export async function generateNarration(id:string){const p=projects.get(id);if(!p)throw Error("Projeto não encontrado");projects.setStatus(id,"generating_narration",80);for(const s of p.scenes){const r=await tts.synthesize(s.narration,p.settings);db.prepare("UPDATE scenes SET audio_url=?,estimated_duration=?,status=? WHERE id=?").run(r.url,r.duration,"audio_ready",s.id)}projects.setStatus(id,"draft",90);return projects.get(id)}
export async function render(id:string){const p=projects.get(id);if(!p)throw Error("Projeto não encontrado");projects.setStatus(id,"rendering",95);await new Promise(r=>setTimeout(r,300));projects.setStatus(id,"completed",100);return projects.get(id)}
export async function auto(id:string){const p=projects.get(id);if(p?.mode==="title")await generateScript(id);await generateScenes(id);await generateImages(id);await generateAnimations(id);await generateNarration(id);return render(id)}
export async function regenerateScene(id:number,type:string){const s=db.prepare("SELECT * FROM scenes WHERE id=?").get(id) as any;if(!s)throw Error("Cena não encontrada");if(type==="image"){const prompt=await llm.generateImagePrompt(s,{});const r=await image.generate(prompt);db.prepare("UPDATE scenes SET image_prompt=?,image_url=? WHERE id=?").run(prompt,r.url,id)}else if(type==="video"){const r=await video.generate(s.image_url,s.animation_prompt,s.estimated_duration);db.prepare("UPDATE scenes SET video_url=? WHERE id=?").run(r.url,id)}else if(type==="audio"){const r=await tts.synthesize(s.narration,{});db.prepare("UPDATE scenes SET audio_url=?,estimated_duration=? WHERE id=?").run(r.url,r.duration,id)}return s}